version: '3.8'

services:
  postgres:
    image: postgres:15.2
    container_name: tg-roommates-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: tg-roommates-redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    networks:
      - backend

  backend:
    build:
      context: .
    container_name: tg-roommates-backend
    restart: always
    depends_on:
      - postgres
      - redis
    env_file: .env
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend: